name: Firebase Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: w9jds/firebase-action@v13.4.0
        env:
          GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Setup Node.js 16'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Deploy functions'
        uses: w9jds/firebase-action@v13.4.0
        with:
          args: 'deploy --only functions'
        env:
          GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
          PROJECT_PATH: './firebase'
      - name: 'Deploy firestore'
        uses: w9jds/firebase-action@v13.4.0
        with:
          args: 'deploy --only firestore --force'
        env:
          GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
          PROJECT_PATH: './firebase'
